class _Links():
    BASE_URL = "https://es-club.spb.ru/"
    ENDPOINT_USLUGI = "about/uslugi/"
    ENDPOINT_SALE = "about/sale/"
    ENDPOINT_ABOUT = "about/"
    ENDPOINT_ABOUT_MEDIA = "about/media/"
    ENDPOINT_ABOUT_OTZYVY = "about/otzyvy/"
    ENDPOINT_ABOUT_WORKPLACE = "about/workplace/"
    ENDPOINT_ABOUT_SALE_DEN_KLIENTA = "about/sale/den-klienta/"
    ENDPOINT_ABOUT_3D = "about/3d/"
